"""Adicionar botao yahoo finance

Revision ID: 0b67a00583b4
Revises: 27c3ec9c9b7f
Create Date: 2025-07-31 19:15:49.695817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b67a00583b4'
down_revision: Union[str, Sequence[str], None] = '27c3ec9c9b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
