"""Acrescentar calculo preco teto com YF

Revision ID: 27c3ec9c9b7f
Revises: 1fdd61d847f5
Create Date: 2025-07-31 18:57:06.606647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c3ec9c9b7f'
down_revision: Union[str, Sequence[str], None] = '1fdd61d847f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
