"""Add crescimento_estimado_lucro to dados_financeiros

Revision ID: 3de63653e237
Revises: cd11ab468bf4
Create Date: 2025-07-31 15:02:20.100853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de63653e237'
down_revision: Union[str, Sequence[str], None] = 'cd11ab468bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
