"""revertendo calculos - Schemas - crud - empresas 2

Revision ID: 5d9f7fdefaf2
Revises: d55ad924e3d5
Create Date: 2025-08-08 09:56:32.530758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9f7fdefaf2'
down_revision: Union[str, Sequence[str], None] = 'd55ad924e3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
