"""create tables

Revision ID: 68bd90f9bb50
Revises: 4dd1e06f7c84
Create Date: 2025-07-25 13:59:15.920852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bd90f9bb50'
down_revision: Union[str, Sequence[str], None] = '4dd1e06f7c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    #op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    #op.drop_index(op.f('ix_empresas_ticker'), table_name='empresas')
    #op.drop_table('empresas')
    #op.drop_index(op.f('ix_dados_financeiros_id'), table_name='dados_financeiros')
    #op.drop_table('dados_financeiros')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_financeiros',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lucro_t1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lucro_t2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lucro_t3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lucro_t4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividendo_por_acao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payout_projetado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ajuste_dividendo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preco_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cagr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tipo_analise', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ajuste_motivo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vantagens', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desvantagens', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lucro_liquido_anual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpa_estimada', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividendo_projetado_calc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preco_teto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('margem', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('dados_financeiros_empresa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dados_financeiros_pkey'))
    )
    op.create_index(op.f('ix_dados_financeiros_id'), 'dados_financeiros', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numero_acoes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('empresas_pkey'))
    )
    op.create_index(op.f('ix_empresas_ticker'), 'empresas', ['ticker'], unique=True)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    # ### end Alembic commands ###
