"""Ajustar recomendação

Revision ID: 6bd8c7f5e307
Revises: b93d4e696e57
Create Date: 2025-08-12 17:56:00.462389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd8c7f5e307'
down_revision: Union[str, Sequence[str], None] = 'b93d4e696e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'recomendacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('recomendacao', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
