"""empty message

Revision ID: c6fc13d90cbe
Revises: 4be6c0b69457
Create Date: 2025-08-05 11:35:47.900209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fc13d90cbe'
down_revision: Union[str, Sequence[str], None] = '4be6c0b69457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'ultima_atualizacao')
    # ### end Alembic commands ###
