"""inserindo GEMINI - Schemas - crud - empresas

Revision ID: d508720c620f
Revises: 5de244a797e4
Create Date: 2025-08-08 10:36:57.814782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd508720c620f'
down_revision: Union[str, Sequence[str], None] = '5de244a797e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
