"""Remover editar yield

Revision ID: f49dcbf16d91
Revises: 4e3522ee9fd0
Create Date: 2025-08-06 14:54:41.145164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49dcbf16d91'
down_revision: Union[str, Sequence[str], None] = '4e3522ee9fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracoes_chave'), table_name='configuracoes')
    op.drop_index(op.f('ix_configuracoes_id'), table_name='configuracoes')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chave', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('configuracoes_pkey'))
    )
    op.create_index(op.f('ix_configuracoes_id'), 'configuracoes', ['id'], unique=False)
    op.create_index(op.f('ix_configuracoes_chave'), 'configuracoes', ['chave'], unique=True)
    # ### end Alembic commands ###
