"""Editar Yield via frontend

Revision ID: f5d78d2926e3
Revises: decd7c5e1a6f
Create Date: 2025-08-06 13:41:10.133495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d78d2926e3'
down_revision: Union[str, Sequence[str], None] = 'decd7c5e1a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_chave'), 'configuracoes', ['chave'], unique=True)
    op.create_index(op.f('ix_configuracoes_id'), 'configuracoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracoes_id'), table_name='configuracoes')
    op.drop_index(op.f('ix_configuracoes_chave'), table_name='configuracoes')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
