"""Atualizando calculos - Schemas - crud - empresas

Revision ID: 02372e7d89e7
Revises: 59d9eb813bce
Create Date: 2025-08-08 09:46:52.347690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02372e7d89e7'
down_revision: Union[str, Sequence[str], None] = '59d9eb813bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
