"""Add lpa_anterior field

Revision ID: 09703ab1776b
Revises: 23dcb5867701
Create Date: 2025-07-31 11:54:46.736762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09703ab1776b'
down_revision: Union[str, Sequence[str], None] = '23dcb5867701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('lpa_anterior', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'lpa_anterior')
    # ### end Alembic commands ###
