"""Add lpa_anterior to lpa field

Revision ID: 0aa04162fa8e
Revises: 09703ab1776b
Create Date: 2025-07-31 12:10:24.730982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa04162fa8e'
down_revision: Union[str, Sequence[str], None] = '09703ab1776b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('lpa', sa.Float(), nullable=True))
    op.drop_column('dados_financeiros', 'lpa_anterior')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('lpa_anterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('dados_financeiros', 'lpa')
    # ### end Alembic commands ###
