"""Add YoY field

Revision ID: 1307e220f9a5
Revises: 0aa04162fa8e
Create Date: 2025-07-31 14:06:54.749860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1307e220f9a5'
down_revision: Union[str, Sequence[str], None] = '0aa04162fa8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('variacao_yoy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'variacao_yoy')
    # ### end Alembic commands ###
