"""revertendo calculos - Schemas - crud - empresas 2

Revision ID: 1dc5038c5496
Revises: 5d9f7fdefaf2
Create Date: 2025-08-08 10:02:01.901264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc5038c5496'
down_revision: Union[str, Sequence[str], None] = '5d9f7fdefaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
