"""Acrescentar Yfinance

Revision ID: 1fdd61d847f5
Revises: bd831c1aa484
Create Date: 2025-07-31 18:33:39.807155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fdd61d847f5'
down_revision: Union[str, Sequence[str], None] = 'bd831c1aa484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('preco_yf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'preco_yf')
    # ### end Alembic commands ###
