"""inserindo preco_atual

Revision ID: 2cc4a93947f4
Revises: c7cbd9b69bd5
Create Date: 2025-08-09 11:49:22.780652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc4a93947f4'
down_revision: Union[str, Sequence[str], None] = 'c7cbd9b69bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'preco_atual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('preco_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
