"""Atualizar dados apenas do ano mais recente

Revision ID: 37721c5993b3
Revises: d4db2707b83d
Create Date: 2025-08-12 12:08:21.174356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37721c5993b3'
down_revision: Union[str, Sequence[str], None] = 'd4db2707b83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
