"""atualizando calculos - Schemas - crud - empresas GEMINI

Revision ID: 3c6421435510
Revises: 1dc5038c5496
Create Date: 2025-08-08 10:12:11.015282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6421435510'
down_revision: Union[str, Sequence[str], None] = '1dc5038c5496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
