"""inserindo preco_atual

Revision ID: 40cfdb6c2a11
Revises: 2cc4a93947f4
Create Date: 2025-08-09 11:51:15.561246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cfdb6c2a11'
down_revision: Union[str, Sequence[str], None] = '2cc4a93947f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('preco_atual', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'preco_atual')
    # ### end Alembic commands ###
