"""Editar Yield via frontend 2

Revision ID: 4e3522ee9fd0
Revises: f5d78d2926e3
Create Date: 2025-08-06 14:20:51.536734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3522ee9fd0'
down_revision: Union[str, Sequence[str], None] = 'f5d78d2926e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
