"""Ajustar recomendação

Revision ID: adb3cbce39dc
Revises: 6bd8c7f5e307
Create Date: 2025-08-12 18:09:10.135090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb3cbce39dc'
down_revision: Union[str, Sequence[str], None] = '6bd8c7f5e307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
