"""Inserir Yield Projetado

Revision ID: b93d4e696e57
Revises: 37721c5993b3
Create Date: 2025-08-12 17:08:44.480611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93d4e696e57'
down_revision: Union[str, Sequence[str], None] = '37721c5993b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('yield_projetado', sa.Float(), nullable=True))
    op.add_column('dados_financeiros', sa.Column('cotacao_yf', sa.Float(), nullable=True))
    op.drop_column('dados_financeiros', 'preco_atual')
    op.drop_column('dados_financeiros', 'preco_yf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('preco_yf', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dados_financeiros', sa.Column('preco_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('dados_financeiros', 'cotacao_yf')
    op.drop_column('dados_financeiros', 'yield_projetado')
    # ### end Alembic commands ###
