"""Add recomendacao

Revision ID: bad6e2a6521d
Revises: 66dedbf15241
Create Date: 2025-07-31 16:32:11.926629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad6e2a6521d'
down_revision: Union[str, Sequence[str], None] = '66dedbf15241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('recomendacao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'recomendacao')
    # ### end Alembic commands ###
