"""revertendo GEMINI - Schemas - crud - empresas

Revision ID: c7cbd9b69bd5
Revises: d508720c620f
Create Date: 2025-08-08 10:46:15.540112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7cbd9b69bd5'
down_revision: Union[str, Sequence[str], None] = 'd508720c620f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
