"""Add crescimento_estimado_lucro to dados_financeiros

Revision ID: cd11ab468bf4
Revises: 1307e220f9a5
Create Date: 2025-07-31 14:32:42.344015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd11ab468bf4'
down_revision: Union[str, Sequence[str], None] = '1307e220f9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados_financeiros', sa.Column('crescimento_estimado_lucro', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_financeiros', 'crescimento_estimado_lucro')
    # ### end Alembic commands ###
