"""revertendo calculos - Schemas - crud - empresas

Revision ID: d55ad924e3d5
Revises: 02372e7d89e7
Create Date: 2025-08-08 09:52:33.815246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55ad924e3d5'
down_revision: Union[str, Sequence[str], None] = '02372e7d89e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
