"""create tables

Revision ID: f9d36b709795
Revises: 32bf27d64735
Create Date: 2025-07-25 16:39:55.506079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d36b709795'
down_revision: Union[str, Sequence[str], None] = '32bf27d64735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('numero_acoes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=True)
    op.create_index(op.f('ix_empresas_ticker'), 'empresas', ['ticker'], unique=True)
    op.create_table('dados_financeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('lucro_t1', sa.Float(), nullable=True),
    sa.Column('lucro_t2', sa.Float(), nullable=True),
    sa.Column('lucro_t3', sa.Float(), nullable=True),
    sa.Column('lucro_t4', sa.Float(), nullable=True),
    sa.Column('dividendo_por_acao', sa.Float(), nullable=True),
    sa.Column('payout_projetado', sa.Float(), nullable=True),
    sa.Column('ajuste_dividendo', sa.Float(), nullable=True),
    sa.Column('preco_atual', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('tipo_analise', sa.String(), nullable=True),
    sa.Column('ajuste_motivo', sa.String(), nullable=True),
    sa.Column('vantagens', sa.String(), nullable=True),
    sa.Column('desvantagens', sa.String(), nullable=True),
    sa.Column('lucro_liquido_anual', sa.Float(), nullable=True),
    sa.Column('lpa_estimada', sa.Float(), nullable=True),
    sa.Column('dividendo_projetado_calc', sa.Float(), nullable=True),
    sa.Column('preco_teto', sa.Float(), nullable=True),
    sa.Column('margem', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dados_financeiros_id'), 'dados_financeiros', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dados_financeiros_id'), table_name='dados_financeiros')
    op.drop_table('dados_financeiros')
    op.drop_index(op.f('ix_empresas_ticker'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
